apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
      kompose.cmd: kompose convert
      kompose.version: 1.35.0 (9532ceef3)
   labels:
      io.kompose.service: viatab
   name: viatab
spec:
   replicas: 1
   selector:
      matchLabels:
         io.kompose.service: viatab
   template:
      metadata:
         annotations:
            kompose.cmd: kompose convert
            kompose.version: 1.35.0 (9532ceef3)
         labels:
            io.kompose.service: viatab
      spec:
         containers:
            - env:
                 - name: SPRING_DATASOURCE_PASSWORD
                   value: Password1
                 - name: SPRING_DATASOURCE_URL
                   value: jdbc:postgresql://db:5432/viatab
                 - name: SPRING_DATASOURCE_USERNAME
                   value: postgres
                 - name: SPRING_JPA_HIBERNATE_DDL_AUTO
                   value: update
              image: viatab:latest
              imagePullPolicy: Never
              name: viatab
              ports:
                 - containerPort: 8080
                   protocol: TCP
         restartPolicy: Always
