apiVersion: apps/v1
kind: Deployment
metadata:
   name: viatab
spec:
   replicas: 1
   selector:
      matchLabels:
         app: viatab
   template:
      metadata:
         labels:
            app: viatab
      spec:
         containers:
            - name: viatab
              image: viatab:latest
              imagePullPolicy: Never
              ports:
                 - containerPort: 8080
              env:
                 - name: SPRING_DATASOURCE_URL
                   value: jdbc:postgresql://viatab-db:5432/viatab
                 - name: SPRING_DATASOURCE_USERNAME
                   value: postgres
                 - name: SPRING_DATASOURCE_PASSWORD
                   value: Password1
                 - name: SPRING_JPA_HIBERNATE_DDL_AUTO
                   value: update
