name: CI

on:
   push:
      branches: [main, master]
   pull_request:

jobs:
   backend:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
              java-version: 21
              distribution: "temurin"
         - name: Build and test backend
           run: |
              cd viatab
              mvn clean install
         - name: Generate JaCoCo coverage report
           run: |
              cd viatab
              mvn jacoco:report
         - name: Upload coverage report
           uses: actions/upload-artifact@v4
           with:
              name: jacoco-report
              path: viatab/target/site/jacoco/

   frontend:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "20"
              cache: "npm"
         - name: Show directory contents
           run: ls -la
         - name: Install dependencies
           run: |
              cd viatab-frontend
              npm install
         - name: Fix react-scripts permissions
           run: |
              cd viatab-frontend
              chmod +x node_modules/.bin/react-scripts
         - name: Run frontend tests
           run: |
              cd viatab-frontend
              npm test
